<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="gov.nasa.jpf.test.basic.HarnessTest" tests="6" skipped="0" failures="0" errors="0" timestamp="2018-10-23T18:35:04" hostname="boombox" time="0.436">
  <properties/>
  <testcase name="verifyAssert" classname="gov.nasa.jpf.test.basic.HarnessTest" time="0.25"/>
  <testcase name="verifyJPFExcept" classname="gov.nasa.jpf.test.basic.HarnessTest" time="0.002"/>
  <testcase name="noViolation" classname="gov.nasa.jpf.test.basic.HarnessTest" time="0.051"/>
  <testcase name="testLowLevelAPI" classname="gov.nasa.jpf.test.basic.HarnessTest" time="0.046"/>
  <testcase name="verifyRuntimeException" classname="gov.nasa.jpf.test.basic.HarnessTest" time="0.046"/>
  <testcase name="verifyNullPointerException" classname="gov.nasa.jpf.test.basic.HarnessTest" time="0.04"/>
  <system-out><![CDATA[  running jpf with args:
JavaPathfinder core system v8.0 (rev 28c066f86c2cd268b8c9b9959161e3d07c6146c6) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.basic.HarnessTest.runTestMethod()

====================================================== search started: 23/10/18 19:35
** this is verifyAssert() - JPF should find an AssertionError

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.AssertionError: wrong answer..
	at gov.nasa.jpf.test.basic.HarnessTest.verifyAssert(HarnessTest.java:48)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:650)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.AssertionError: wrong answer..  at gov.n..."

====================================================== search finished: 23/10/18 19:35
  running jpf with args: +vm.class=InvalidVMClass +pass_exceptions
[SEVERE] JPF configuration error: class not found InvalidVMClass by classloader: gov.nasa.jpf.JPFClassLoader@6e8d0fca
  running jpf with args:
JavaPathfinder core system v8.0 (rev 28c066f86c2cd268b8c9b9959161e3d07c6146c6) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.basic.HarnessTest.runTestMethod()

====================================================== search started: 23/10/18 19:35
** this is noViolation() - it should succeed

====================================================== results
no errors detected

====================================================== search finished: 23/10/18 19:35
  running jpf with args:
JavaPathfinder core system v8.0 (rev 28c066f86c2cd268b8c9b9959161e3d07c6146c6) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.basic.HarnessTest.runTestMethod()

====================================================== search started: 23/10/18 19:35
** this is low level API test - it should succeed

====================================================== results
no errors detected

====================================================== search finished: 23/10/18 19:35
  running jpf with args:
JavaPathfinder core system v8.0 (rev 28c066f86c2cd268b8c9b9959161e3d07c6146c6) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.basic.HarnessTest.runTestMethod()

====================================================== search started: 23/10/18 19:35
** this is verifyRuntimeException() - JPF should find an unhandled exception

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.RuntimeException: Bang!
	at gov.nasa.jpf.test.basic.HarnessTest.verifyRuntimeException(HarnessTest.java:68)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:650)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.RuntimeException: Bang!  at gov.nasa.jpf..."

====================================================== search finished: 23/10/18 19:35
  running jpf with args:
JavaPathfinder core system v8.0 (rev 28c066f86c2cd268b8c9b9959161e3d07c6146c6) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
gov.nasa.jpf.test.basic.HarnessTest.runTestMethod()

====================================================== search started: 23/10/18 19:35
** this is verifyNullPointerException() - JPF should find an NPE

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NullPointerException: Calling 'length()I' on null object
	at gov.nasa.jpf.test.basic.HarnessTest.verifyNullPointerException(HarnessTest.java:59)
	at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)


====================================================== snapshot #1
thread java.lang.Thread:{id:0,name:main,status:RUNNING,priority:5,isDaemon:false,lockCount:0,suspendCount:0}
  call stack:
	at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:650)


====================================================== results
error #1: gov.nasa.jpf.vm.NoUncaughtExceptionsProperty "java.lang.NullPointerException: Calling 'length()I..."

====================================================== search finished: 23/10/18 19:35
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
